config/routes.rb
Classifieds::Application.routes.draw do

  resources :leads

  get "pages/home"

  resources :adverts

  resources :categories

  resources :users

  get "adverts/index"

  root :to => 'pages#home'

  get 'my_account' => 'member#account'

  controller :session do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

end

app/models/advert.rb
class Advert < ActiveRecord::Base
  attr_accessible :category_id, :contact_details, :description, :title, :user_id, :approved, :image
  belongs_to :category
  belongs_to :user
  has_many  :leads

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  def self.approved
    where(approved: true)
  end

end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController

  before_filter :member_required, except: [:show]

  before_filter :set_advert, except: [:show]

  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = @advert_class.all
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
    @advert = Advert.find(params[:id])
    @lead = @advert.leads.new

    redirect_to :root if !@advert.approved? and !owner_of?(@advert)

  end

  # GET /adverts/new
  # GET /adverts/new.json
  def new
    @advert = @advert_class.new
  end

  # GET /adverts/1/edit
  def edit
    @advert = @advert_class.find(params[:id])
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = @advert_class.new(params[:advert])

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render json: @advert, status: :created, location: @advert }
      else
        format.html { render action: "new" }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adverts/1
  # PUT /adverts/1.json
  def update
    @advert = @advert_class.find(params[:id])

    respond_to do |format|
      if @advert.update_attributes(params[:advert])
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert = @advert_class.find(params[:id])
    @advert.destroy

    respond_to do |format|
      format.html { redirect_to adverts_url }
      format.json { head :no_content }
    end
  end

  private

  def set_advert
    if admin?
      @advert_class = Advert
    else
      @advert_class = current_user.adverts
    end
  end

end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/views/adverts/_form.html.erb
<%= simple_form_for @advert, :html => { :multipart => true } do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <% if admin? %>
          <%= f.association :user %>
          <%= f.input :approved %>
      <% end %>
      <%= f.input :title %>
      <%= f.input :image %>
      <%= f.input :description %>
      <%= f.input :contact_details %>
      <%= f.association :category, as: :radio_buttons %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/adverts/edit.html.erb
<h1>Editing advert</h1>

<%= render 'form' %>

<%= link_to 'Show', @advert %> |
<%= link_to 'Back', adverts_path %>

app/views/adverts/index.html.erb
<h1>Listing adverts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @adverts.each do |advert| %>
  <tr>
    <td><%= advert.title %></td>
    <td><%= advert.category.name %></td>
    <td><%= link_to 'Show', advert %></td>
    <td><%= link_to 'Edit', edit_advert_path(advert) %></td>
    <td><%= link_to 'Destroy', advert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Advert', new_advert_path %>

app/views/adverts/new.html.erb
<h1>New advert</h1>

<%= render 'form' %>

<%= link_to 'Back', adverts_path %>

app/views/adverts/show.html.erb
<h1>
  <%= @advert.title %>
</h1>
<br/>
<p>
  <%= image_tag @advert.image %>
</p>

<p>
  <b>Description:</b>
  <%= @advert.description %>
</p>

<p>
  <b>Contact details:</b>
  <%= @advert.contact_details %>
</p>

<p>
  <b>Category:</b>
  <%= @advert.category.name %>
</p>

<% if admin? || owner_of?(@advert) %>
    <%= link_to 'Edit', edit_advert_path(@advert) %>
<% end %>

<h2>Contact The Owner</h2>

<%= render "leads/form" %>